export const BUSINESS = ["TAMQO", "LOGIX"];
export const BUSINESS_TYPES = ["TAMQO_ONLY", "LOGIX_ONLY", "PARTNERSHIP"];
export const STATUSES = [
  "NEW",
  "CONFIRMED",
  "PREPARING",
  "READY_TO_SHIP",
  "SHIPPED",
  "OUT_FOR_DELIVERY",
  "DELIVERED",
  "FAILED_DELIVERY",
  "RETURNING",
  "RETURNED",
  "CANCELLED",
];
export const PAYMENT_METHODS = ["COD", "ONLINE", "MIXED"];
export const DELIVERY_TYPES = ["HOME", "STOP_DESK"];
export const TERMINAL = ["DELIVERED", "RETURNED", "CANCELLED"];
export const TRANSITIONS = {
  NEW: ["CONFIRMED", "CANCELLED"],
  CONFIRMED: ["PREPARING", "CANCELLED"],
  PREPARING: ["READY_TO_SHIP", "CANCELLED"],
  READY_TO_SHIP: ["SHIPPED", "CANCELLED"],
  SHIPPED: ["OUT_FOR_DELIVERY", "DELIVERED", "FAILED_DELIVERY", "RETURNING"],
  OUT_FOR_DELIVERY: ["DELIVERED", "FAILED_DELIVERY", "RETURNING"],
  FAILED_DELIVERY: ["OUT_FOR_DELIVERY", "DELIVERED", "RETURNING"],
  RETURNING: ["RETURNED"],
  DELIVERED: [],
  RETURNED: [],
  CANCELLED: [],
};
